name: Cas pràctic 6
run-name: ${{ github.actor }} executant cas pràctic 6 (ZIP amb secrets)
on: workflow_dispatch

jobs:
  descomprimir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositori
        uses: actions/checkout@v4
      
      - name: Instal·la unzip
        run: sudo apt-get install unzip
        
      - name: Descomprimeix el fitxer zip
        run: unzip -P ${{ secrets.ZIP_PWD }} secret.zip
        
      - name: Mostra el contingut de secret.txt
        run: cat secret.txt
